
import form.FormMahasiswa;
import form.FrameDataMahasiswa;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yanua
 */
public class FrameUtama extends javax.swing.JFrame {
    public static class UIBaru extends Component
    {
        // konstruktor
        public UIBaru()
        {
            
        }
    }
    
    /**
     * Creates new form FrameUtama
     */
    public FrameUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuitemKeluar = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuitemDataMahasiswa = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        menuitemDataDosen = new javax.swing.JMenuItem();
        menuAboutUs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        menuitemKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        menuitemKeluar.setText("Keluar");
        menuitemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemKeluarActionPerformed(evt);
            }
        });
        menuFile.add(menuitemKeluar);

        menubar.add(menuFile);

        menuLaporan.setText("Laporan");

        menuitemDataMahasiswa.setText("Data Mahasiswa");
        menuitemDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDataMahasiswaActionPerformed(evt);
            }
        });
        menuLaporan.add(menuitemDataMahasiswa);
        menuLaporan.add(separator);

        menuitemDataDosen.setText("Data Dosen");
        menuitemDataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDataDosenActionPerformed(evt);
            }
        });
        menuLaporan.add(menuitemDataDosen);

        menubar.add(menuLaporan);

        menuAboutUs.setText("About Us");
        menubar.add(menuAboutUs);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuitemKeluarActionPerformed

    private void menuitemDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDataMahasiswaActionPerformed
        panelUtama.removeAll();
        panelUtama.repaint();
        FrameDataMahasiswa frameDataMahasiswa = new FrameDataMahasiswa();
        
        // sizescreen
        Dimension layarUtama = this.getSize();
        Dimension layarMahasiswa = frameDataMahasiswa.getSize();
        
        // simpan posisi frame mahasiswa di tengah layar utama
        frameDataMahasiswa.setLocation(
            layarUtama.width / 2 - layarMahasiswa.width / 2,
            layarUtama.height / 2 - layarMahasiswa.height / 2
        );
        
        panelUtama.add(frameDataMahasiswa);
        frameDataMahasiswa.setVisible(true);
    }//GEN-LAST:event_menuitemDataMahasiswaActionPerformed

    private void menuitemDataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDataDosenActionPerformed
        panelUtama.removeAll();
        panelUtama.repaint();
        
        FormMahasiswa dosen = new FormMahasiswa();
        dosen.setVisible(true);
        panelUtama.add(dosen);
    }//GEN-LAST:event_menuitemDataDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Cara pake JTattoo
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new UIBaru());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error karena: " + e.getMessage());
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAboutUs;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemDataDosen;
    private javax.swing.JMenuItem menuitemDataMahasiswa;
    private javax.swing.JMenuItem menuitemKeluar;
    private javax.swing.JDesktopPane panelUtama;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
